steps:

# 1. Construir la imagen de Docker
# Se recomienda usar tags inmutables como el SHA del commit ($SHORT_SHA) en lugar de 'latest'.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest',
    '.'
  ]

# 2. Subir la imagen construida a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest']


# 3. Desplegar el servicio en Cloud Run usando el archivo declarativo service.yaml
# Este comando crea una nueva revisión del servicio. Si 'service.yaml' referencia
# la imagen con el tag 'latest', Cloud Run obtendrá la versión más reciente de la imagen.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'services'
  - 'replace'
  - 'service.yaml'
  - '--platform=managed'
  - '--region=us-central1'


# Especifica la imagen que se acaba de construir para que esté disponible para los siguientes pasos
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest'

# Opciones de configuración
options:
  # Nivel de logging para ver los detalles del build
  logging: CLOUD_LOGGING_ONLY
