steps:
# 1. Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest',
    '.'
  ]

# 2. Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest']

# 3. Desplegar la nueva imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'sofia-salesforce-api-service' # El nombre de tu servicio en Cloud Run
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest'
  - '--platform=managed'
  - '--region=us-central1'
  # Inyecta los secretos de Secret Manager en el servicio de Cloud Run.
  # 1. Monta la clave privada como un archivo dentro del contenedor.
  - '--set-secrets=/app/server.key=sf-prod-private-key:latest'
  # 2. Inyecta las otras credenciales como variables de entorno.
  - '--set-secrets=SF_USERNAME=sf-prod-username:latest,SF_CONSUMER_KEY=sf-prod-consumer-key:latest,SF_DOMAIN=sf-prod-domain:latest'
  # 3. Asegúrate de que la variable que apunta al archivo de la clave sea correcta.
  #    Tu app.py usa os.getenv("SF_PRIVATE_KEY_FILE"), que localmente es "server.key".
  #    Como montamos el archivo en /app/server.key, el valor "server.key" sigue siendo correcto.

# Especifica la imagen que se acaba de construir para que esté disponible para los siguientes pasos
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:latest'

# Opciones de configuración
options:
  # Nivel de logging para ver los detalles del build
  logging: CLOUD_LOGGING_ONLY