steps:

# 1. Construir la imagen de Docker usando el SHA del commit como tag
# Usar $SHORT_SHA en lugar de 'latest' es una buena práctica para tener tags inmutables y únicos.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:$SHORT_SHA',
    '.'
  ]

# 2. Subir la imagen construida a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:$SHORT_SHA']


# 3. Desplegar la imagen en Cloud Run de forma imperativa
# Este comando crea o actualiza el servicio 'sofia-salesforce-api' con la nueva imagen.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'sofia-salesforce-api' # El nombre de tu servicio en Cloud Run
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:$SHORT_SHA'
  - '--platform=managed'
  - '--region=us-central1'
  #


# Especifica la imagen que se acaba de construir para que esté disponible para los siguientes pasos
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/sofia-salesforce-api-repo/sofia-salesforce-api:$SHORT_SHA'

# Opciones de configuración
options:
  # Nivel de logging para ver los detalles del build
  logging: CLOUD_LOGGING_ONLY
